# Use MICRONAUT_ENVIRONMENTS=dev to activate this environment

micronaut:
  server:
  #port: 8081 # default: -1 (random port)
  http:
    # manual service discovery; should be disabled in docker-compose deployment; is useful when developing but running other services as docker container
    services:
      planners:
        urls:
          - http://localhost:8083/
  security:
    default: false
    #enabled: true

# Disable service discovery and registration
consul:
  client:
    discovery:
      enabled: false
    registration:
      enabled: false

datasources:
  # H2 in-memory
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
#  # H2 persistent
#  default:
#    url: jdbc:h2:./data/micronaut-data/h2;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    #schema-generate: UPDATE
#    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          # TODO: might be more interesting once Liquibase is used
          auto: update



