image:
  file: .gitpod.Dockerfile

tasks:
  - name: Backend
    init: |
      echo ðŸ§ GitPod Tasks -> Backend -> Init
      ./gradlew :backend:build
      echo ðŸ§ GitPod Tasks -> Backend -> Init done
    command: |
      echo ðŸ§ GitPod Tasks -> Backend -> Command
      MICRONAUT_ENVIRONMENTS=dev ./gradlew :backend:run
      echo ðŸ§ GitPod Tasks -> Backend -> Command done
  # - name: Planner
  #   init: ./gradlew :planner:build
  #   command: ./gradlew :planner:run
  - name: Angular
    init: |
      echo ðŸ§ GitPod Tasks -> Angular -> Init
      cd /workspace/walkingdinner/web-angular
      npm install
      echo ðŸ§ GitPod Tasks -> Angular -> Init done
    command: |
      echo ðŸ§ GitPod Tasks -> Angular -> Command
      cd /workspace/walkingdinner/web-angular
      npm start
      echo ðŸ§ GitPod Tasks -> Angular -> Command done

ports:
  # Backend
  - port: 8081
    onOpen: ignore
  # Angular
  - port: 4200
    onOpen: open-browser
    #onOpen: open-preview
  # Planners
  - port: 8083
    onOpen: ignore

vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    # code completion for application.yml (see: https://docs.micronaut.io/latest/guide/index.html#vsCodeSetup)
    - Pivotal.vscode-spring-boot@1.20.0:jaH7mimG3KKfktrKqHw8Kg==
    
    # TODO: copied from gitpod typescript template
    #- dbaeumer.vscode-eslint