language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test build

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Marc Kohaupt (Travis CI)"
  - git config --local user.email "debuglevel@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  
deploy:
  provider: releases
  api_key: "89edc86662ad960310f227d129dc604b0335b91b"
  file_glob: true
  file: build/libs/geneticplanner-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
