version: '3'
services:
  rest:
    build: .
    image: walkingdinner-rest
    ports:
      - "8081:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
  angular:
    build: web-angular
    image: walkingdinner-angular
    ports:
      - "8082:80"
    environment:
      - API_URL=http://localhost:8081