version: '3'
services:

  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    image: walkingdinner-rest
    ports:
      - "8081:8081"
    environment:
      # port 8080 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=8081
      #      # log as JSON
      #      - LOG_APPENDER=json-stdout
      #      # enable health check if Consul is used
      #      - CONSUL_CLIENT_HEALTH_CHECK=true
      #      # register this service on Consul
      #      - CONSUL_CLIENT_REGISTRATION_ENABLED=true
      #      # search for services on Consul
      #      - CONSUL_CLIENT_DISCOVERY_ENABLED=true
      # Consul server
      - CONSUL_HOST=consul
      #      - CONSUL_PORT=8500
      # service must know its own hostname to publish it in service discovery
      - MICRONAUT_SERVER_HOST=rest
      # manual service discovery
      #- MICRONAUT_HTTP_SERVICES_PLANNER_URLS=http://planner:8083
      - APP_WALKINGDINNER_DATA_BASEPATH=/data
      - DATASOURCES_DEFAULT_URL=jdbc:h2:/data/micronaut-data/h2;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    volumes:
      - walkingdinner-rest-data:/data

  angular:
    build:
      context: web-angular
    image: walkingdinner-angular
    ports:
      - "8082:80"
    environment:
      - API_URL=http://localhost:8081

  planner:
    build:
      context: .
      dockerfile: planner/Dockerfile
    image: walkingdinner-planner
    ports:
      - "8083:8083"
    environment:
      # port 8080 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=8083
      #      # log as JSON
      #      - LOG_APPENDER=json-stdout
      #      # enable health check if Consul is used
      #      - CONSUL_CLIENT_HEALTH_CHECK=true
      #      # register this service on Consul
      #      - CONSUL_CLIENT_REGISTRATION_ENABLED=true
      #      # search for services on Consul
      #      - CONSUL_CLIENT_DISCOVERY_ENABLED=true
      # Consul server
      - CONSUL_HOST=consul
      #      - CONSUL_PORT=8500
      # service must know its own hostname to publish it in service discovery
      - MICRONAUT_SERVER_HOST=planner

  # Service registration and discovery with Consul
  consul:
    image: consul:1.10.3
    ports:
      - "8500:8500"

#  # Database and admin tools
#  db:
#    image: mariadb:10.5.8-focal
##    ports:
##      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      # would not create a database if MYSQL_DATABASE is not set
#      - MYSQL_DATABASE=db
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#  postgres:
#    image: postgres:13.2-alpine
#    ports:
#      - 5432:5432
#    environment:
#      # does not seem to work
#      - POSTGRES_DATABASE=db
#      # is (in contrast to mariadb) the superuser
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#  phpmyadmin:
#    image: phpmyadmin:5.0.4
#    ports:
#      - 8090:80
#    environment:
#      - PMA_HOST=db
#      - UPLOAD_LIMIT=1024000
#  adminer:
#    image: adminer:4.7.8-standalone
#    ports:
#      - 8091:8080
#    environment:
#      - ADMINER_DEFAULT_SERVER=db

volumes:
  walkingdinner-rest-data: