version: '3'
services:
  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    image: walkingdinner-rest
    ports:
      - "8081:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
      - MICRONAUT_HTTP_SERVICES_CALCULATION_URLS=http://planners:80/calculations
      - MICRONAUT_HTTP_SERVICES_PLAN_URLS=http://planners:80/plans
  angular:
    build:
      context: web-angular
    image: walkingdinner-angular
    ports:
      - "8082:80"
    environment:
      - API_URL=http://localhost:8081
  planners:
    build:
      context: .
      dockerfile: planners/Dockerfile
    image: walkingdinner-planners
    ports:
      - "8083:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80