version: '3'
services:
  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    image: walkingdinner-rest
    ports:
      - "8081:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
      # service must know its own hostname to publish it in service discovery
      - MICRONAUT_SERVER_HOST=rest
      # manual service discovery
      #- MICRONAUT_HTTP_SERVICES_PLANNERS_URLS=http://planners:80
      # service discovery and registration with Consul
      - CONSUL_HOST=consul
      - APP_WALKINGDINNER_DATA_BASEPATH=/data
    volumes:
      - walkingdinner-rest-data:/data
  angular:
    build:
      context: web-angular
    image: walkingdinner-angular
    ports:
      - "8082:80"
    environment:
      - API_URL=http://localhost:8081
  planners:
    build:
      context: .
      dockerfile: planners/Dockerfile
    image: walkingdinner-planners
    ports:
      - "8083:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
      # service must know its own hostname to publish it in service discovery
      - MICRONAUT_SERVER_HOST=planners
      # service discovery and registration with Consul
      - CONSUL_HOST=consul
  # Service discovery with Consul
  consul:
    # as of 2019-10-09, micronaut only supports 1.2.x
    image: consul:1.2.4
    ports:
      - "8500:8500"